# Generated by Django 5.2.3 on 2025-06-25 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_api', '0005_bookmark_title'),
    ]

    operations = [
    ]
