@echo off
echo Starting web2blog application...

echo Starting backend...
start "Backend" cmd /k "python manage.py runserver"

echo Waiting for backend to initialize...
timeout /t 5 /nobreak >nul

echo Starting frontend...
start "Frontend" cmd /k "cd frontend && npm run dev"

echo Both services are starting...
echo Frontend will be available at http://localhost:5173
echo Backend will be available at http://localhost:8000
echo Press any key to exit...
pause >nul