export const dummyImages = [
  {
    id: 1,
    type: "PNG",
    data: "https://loremflickr.com/400/300/technology?random=1",
  },
  {
    id: 2,
    type: "JPEG",
    data: "https://loremflickr.com/400/300/computer?random=2",
  },
  {
    id: 3,
    type: "PNG",
    data: "https://loremflickr.com/400/300/coding?random=3",
  },
  {
    id: 4,
    type: "JPEG",
    data: "https://loremflickr.com/400/300/programming?random=4",
  },
  {
    id: 5,
    type: "PNG",
    data: "https://loremflickr.com/400/300/web?random=5",
  },
  {
    id: 6,
    type: "JPEG",
    data: "https://loremflickr.com/400/300/design?random=6",
  },
];

export const dummyUsers = [
  {
    id: 1,
    username: "alex_dev",
    email: "alex@example.com",
  },
  {
    id: 2,
    username: "sarah_designs",
    email: "sarah@example.com",
  },
  {
    id: 3,
    username: "mike_codes",
    email: "mike@example.com",
  },
  {
    id: 4,
    username: "emma_tech",
    email: "emma@example.com",
  },
];

export const dummyProfiles = [
  {
    id: 1,
    user: dummyUsers[0],
    biography: "Full Stack Developer passionate about React and TypeScript. Love building scalable web applications.",
    profile_picture: dummyImages[0],
  },
  {
    id: 2,
    user: dummyUsers[1],
    biography: "UI/UX Designer and Frontend Developer. Creating beautiful and functional user experiences.",
    profile_picture: dummyImages[1],
  },
  {
    id: 3,
    user: dummyUsers[2],
    biography: "Backend Engineer specializing in Python and Django. Database optimization enthusiast.",
    profile_picture: dummyImages[2],
  },
  {
    id: 4,
    user: dummyUsers[3],
    biography: "DevOps Engineer and Cloud Architect. Automating everything for better developer experience.",
    profile_picture: dummyImages[3],
  },
];

export const dummyHashtags = [
  { id: 1, value: "javascript" },
  { id: 2, value: "react" },
  { id: 3, value: "typescript" },
  { id: 4, value: "python" },
  { id: 5, value: "django" },
  { id: 6, value: "webdev" },
  { id: 7, value: "frontend" },
  { id: 8, value: "backend" },
  { id: 9, value: "tutorial" },
  { id: 10, value: "beginners" },
  { id: 11, value: "devops" },
  { id: 12, value: "design" },
];

export const dummyPosts = [
  {
    id: 1,
    profile: dummyProfiles[0],
    title: "Getting Started with TypeScript: A Complete Guide",
    content: "TypeScript has become an essential tool for modern JavaScript development. In this comprehensive guide, we'll explore the fundamentals of TypeScript, from basic type annotations to advanced features like generics and decorators. Learn how TypeScript can help you catch errors early and improve your development experience.",
    image: dummyImages[0],
    tags: [dummyHashtags[2], dummyHashtags[0], dummyHashtags[8]],
    draft: false,
    like_count: 42,
    comment_count: 8,
    bookmark_count: 15,
    is_liked: false,
    is_bookmarked: true,
  },
  {
    id: 2,
    profile: dummyProfiles[1],
    title: "Modern UI Design Principles for Web Applications",
    content: "Creating intuitive and beautiful user interfaces requires understanding core design principles. This post covers color theory, typography, spacing, and visual hierarchy. We'll also discuss accessibility considerations and how to create designs that work for everyone.",
    image: dummyImages[5],
    tags: [dummyHashtags[11], dummyHashtags[6], dummyHashtags[5]],
    draft: false,
    like_count: 38,
    comment_count: 12,
    bookmark_count: 22,
    is_liked: true,
    is_bookmarked: false,
  },
  {
    id: 3,
    profile: dummyProfiles[0],
    title: "Building Reusable React Components",
    content: "Learn how to create flexible and reusable React components that can be used across different projects. We'll cover component composition, prop patterns, and best practices for maintainable code.",
    image: dummyImages[1],
    tags: [dummyHashtags[1], dummyHashtags[0], dummyHashtags[6]],
    draft: false,
    like_count: 29,
    comment_count: 6,
    bookmark_count: 11,
    is_liked: false,
    is_bookmarked: false,
  },
  {
    id: 4,
    profile: dummyProfiles[2],
    title: "Django REST API Best Practices",
    content: "Building robust APIs with Django REST Framework requires following established patterns and best practices. This guide covers serializers, viewsets, authentication, permissions, and performance optimization techniques.",
    image: dummyImages[2],
    tags: [dummyHashtags[3], dummyHashtags[4], dummyHashtags[7]],
    draft: false,
    like_count: 51,
    comment_count: 14,
    bookmark_count: 28,
    is_liked: true,
    is_bookmarked: true,
  },
  {
    id: 5,
    profile: dummyProfiles[3],
    title: "Docker for Developers: From Basics to Production",
    content: "Containerization has revolutionized how we deploy applications. Learn Docker fundamentals, best practices for writing Dockerfiles, and how to orchestrate containers in production environments.",
    image: dummyImages[3],
    tags: [dummyHashtags[10], dummyHashtags[8]],
    draft: false,
    like_count: 67,
    comment_count: 19,
    bookmark_count: 35,
    is_liked: false,
    is_bookmarked: false,
  },
  {
    id: 6,
    profile: dummyProfiles[1],
    title: "CSS Grid vs Flexbox: When to Use Which",
    content: "Both CSS Grid and Flexbox are powerful layout tools, but they excel in different scenarios. This post explains the key differences and provides practical examples of when to use each approach.",
    image: dummyImages[4],
    tags: [dummyHashtags[5], dummyHashtags[6], dummyHashtags[8]],
    draft: false,
    like_count: 34,
    comment_count: 9,
    bookmark_count: 18,
    is_liked: true,
    is_bookmarked: false,
  },
  {
    id: 7,
    profile: dummyProfiles[0],
    title: "JavaScript ES2024: New Features You Should Know",
    content: "JavaScript continues to evolve with new features that make development more efficient. Explore the latest additions in ES2024, including new array methods, improved error handling, and performance enhancements.",
    image: dummyImages[0],
    tags: [dummyHashtags[0], dummyHashtags[5]],
    draft: false,
    like_count: 45,
    comment_count: 11,
    bookmark_count: 24,
    is_liked: false,
    is_bookmarked: true,
  },
  {
    id: 8,
    profile: dummyProfiles[2],
    title: "Database Optimization Techniques for Better Performance",
    content: "Slow database queries can kill your application's performance. Learn about indexing strategies, query optimization, connection pooling, and caching techniques to keep your database running smoothly.",
    image: dummyImages[1],
    tags: [dummyHashtags[3], dummyHashtags[7]],
    draft: false,
    like_count: 72,
    comment_count: 16,
    bookmark_count: 41,
    is_liked: true,
    is_bookmarked: true,
  },
  {
    id: 9,
    profile: dummyProfiles[3],
    title: "CI/CD Pipeline Setup with GitHub Actions",
    content: "Automate your development workflow with GitHub Actions. This tutorial covers setting up continuous integration and deployment pipelines, running tests, and deploying to various platforms.",
    image: dummyImages[2],
    tags: [dummyHashtags[10], dummyHashtags[8]],
    draft: false,
    like_count: 58,
    comment_count: 13,
    bookmark_count: 32,
    is_liked: false,
    is_bookmarked: false,
  },
  {
    id: 10,
    profile: dummyProfiles[1],
    title: "Responsive Web Design: Mobile-First Approach",
    content: "Creating websites that work seamlessly across all devices is crucial in today's mobile world. Learn the mobile-first methodology, responsive breakpoints, and testing strategies for optimal user experience.",
    image: dummyImages[5],
    tags: [dummyHashtags[5], dummyHashtags[6], dummyHashtags[11]],
    draft: false,
    like_count: 39,
    comment_count: 7,
    bookmark_count: 19,
    is_liked: true,
    is_bookmarked: false,
  },
  {
    id: 11,
    profile: dummyProfiles[0],
    title: "Advanced React Hooks: Custom Hooks and Patterns",
    content: "Move beyond useState and useEffect with advanced React hooks patterns. Learn to create custom hooks, optimize performance with useMemo and useCallback, and manage complex state with useReducer.",
    image: dummyImages[3],
    tags: [dummyHashtags[1], dummyHashtags[0], dummyHashtags[6]],
    draft: false,
    like_count: 63,
    comment_count: 18,
    bookmark_count: 37,
    is_liked: false,
    is_bookmarked: true,
  },
  {
    id: 12,
    profile: dummyProfiles[2],
    title: "API Security: Protecting Your Backend Services",
    content: "Security should be a top priority when building APIs. This comprehensive guide covers authentication methods, rate limiting, input validation, SQL injection prevention, and monitoring techniques.",
    image: dummyImages[4],
    tags: [dummyHashtags[3], dummyHashtags[4], dummyHashtags[7]],
    draft: false,
    like_count: 81,
    comment_count: 22,
    bookmark_count: 48,
    is_liked: true,
    is_bookmarked: true,
  },
];

export const dummyComments = [
  {
    id: 1,
    post: dummyPosts[0],
    author_profile: dummyProfiles[1],
    content: "Great introduction to TypeScript! Really helped me understand the basics.",
  },
  {
    id: 2,
    post: dummyPosts[0],
    author_profile: dummyProfiles[2],
    content: "The examples are very clear. Would love to see more advanced topics covered.",
  },
];

export const dummyLikes = [
  {
    id: 1,
    post: dummyPosts[0],
    liker_profile: dummyProfiles[1],
  },
  {
    id: 2,
    post: dummyPosts[1],
    liker_profile: dummyProfiles[0],
  },
];

export const dummyBookmarks = [
  {
    id: 1,
    post: dummyPosts[0],
    creator_profile: dummyProfiles[0],
    title: "My favorite TypeScript guide",
  },
  {
    id: 2,
    post: dummyPosts[3],
    creator_profile: dummyProfiles[1],
    title: "Django API reference",
  },
];
