name: Django tests

on:
  push:
    branches: [master, ci-flake]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      DJANGO_SETTINGS_MODULE: backend.settings
      PYTHONUNBUFFERED: '1'

    steps:
      - uses: actions/checkout@v4
      
      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run pytest with coverage (fails < 95 %)
        run: |
          nix develop -c pytest --cov=blog_api --cov-report=xml --cov-report=term-missing --cov-fail-under=95
