name: Django tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      DJANGO_SETTINGS_MODULE: backend.settings
      PYTHONUNBUFFERED: '1'

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-django coverage

      - name: Run pytest with coverage (fails < 95 %)
        run: |
          pytest --cov=blog_api --cov-report=xml --cov-report=term-missing --cov-fail-under=95
